# Generated by Django 4.1.5 on 2023-01-31 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items_registration', '0002_add_items_info_to_user_loaner_and_items_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanermodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
