# Generated by Django 4.1.5 on 2023-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_registration', '0004_restore_user_loner_and_items_model_to_first_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsmodel',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='itemsmodel',
            name='owner_name',
        ),
        migrations.AlterField(
            model_name='printeditemsmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='videoitemsmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
